// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCveIzCQsX5ReXmUrYu1IHPqgEKPgw2sVs',
    appId: '1:793989405526:web:8891052f6d4ed2d9f394f7',
    messagingSenderId: '793989405526',
    projectId: 'testing-attendin',
    authDomain: 'testing-attendin.firebaseapp.com',
    storageBucket: 'testing-attendin.appspot.com',
    measurementId: 'G-P7JFNHJPLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANP-4SnD3bqVrbkcege_-xPzphoYjOhGU',
    appId: '1:793989405526:android:0a1f161efa1d3a0ef394f7',
    messagingSenderId: '793989405526',
    projectId: 'testing-attendin',
    storageBucket: 'testing-attendin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_PIQNnPhTWlEEsa1SeN3aVg514WyBzEo',
    appId: '1:793989405526:ios:c95d1088ad3596a0f394f7',
    messagingSenderId: '793989405526',
    projectId: 'testing-attendin',
    storageBucket: 'testing-attendin.appspot.com',
    iosClientId: '793989405526-l8dguislvnsipoj13rbusrg53athp9d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_PIQNnPhTWlEEsa1SeN3aVg514WyBzEo',
    appId: '1:793989405526:ios:c95d1088ad3596a0f394f7',
    messagingSenderId: '793989405526',
    projectId: 'testing-attendin',
    storageBucket: 'testing-attendin.appspot.com',
    iosClientId: '793989405526-l8dguislvnsipoj13rbusrg53athp9d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendin',
  );
}
